# baseURL = "https://vukilis.github.io/website/"
baseURL = "https://vukilis.com/"
theme = "LoveIt"
# website title
title = "V For Vuk1lis"
languageCode = "en"
languageName = "English"
summaryLength = true
canonifyurls = true

[Permalinks]
    # posts = ":year/:month/:filename"
    posts = ":filename"
# Author config
[author]
    name = "Vuk1lis"
    email = ""
    link = "/about/"

# Menu config
[menu]
    [[menu.main]]
        weight = 1
        identifier = "posts"
        pre = ""
        post = ""
        name = "Posts"
        url = "/posts/"
        # title will be shown when you hover on this menu link
        title = ""
    [[menu.main]]
        weight = 2
        identifier = "tags"
        pre = ""
        post = ""
        name = "Tags"
        url = "/tags/"
        title = ""
    [[menu.main]]
        weight = 3
        identifier = "categories"
        pre = ""
        post = ""
        name = "Categories"
        url = "/categories/"
        title = ""
    [[menu.main]]
        weight = 4
        identifier = "about"
        pre = ""
        post = ""
        name = "About"
        url = "/about/"
        title = ""
    [[menu.main]]
        weight = 5
        identifier = "design.html"
        pre = ""
        post = ""
        name = "Design"
        url = "/design/"
        title = ""

[outputs]
    home = ["HTML", "RSS", "JSON"]

[params.search]
    enable = true
    type = "algolia"
    contentLength = 4000
    placeholder = "search"
    maxResultLength = 10
    snippetLength = 30
    highlightTag = "em"
    absoluteURL = false
    [params.search.algolia]
        index = "website"
        appID = "DAENWQCI5B"
        searchKey = "3a87729afa43d11594394f5b86df56f8"

[params]
    defaultTheme = "dark"
    
    title = "V For Vuk1lis"
    name = "V For Vuk1lis"
    description = "Happy Coding"
    images = ["/images/logo.png"]
    [params.app]
        svgFavicon = "/images/favicon.png"
    [params.header.title]
        logo = "/images/logo.png"
        name = ""
        pre = ""
        post = ""
        typeit = true
    [params.footer]
        enable = true
        custom = ""
        hugo = false
        since = 2023
        license= "Privacy Policy"
        icp = "Terms and Conditions"
    
    [params.home]
    # amount of RSS pages
    rss = 5
    [params.home.profile]
        enable = true
        gravatarEmail = ""
        # URL of avatar shown in home page
        avatarURL = "/images/logo.png"
        title = "V For Vuk1lis"
        subtitle = "This site is made to document all my work, store a different guides and how-to articles."
        typeit = false
        social = true
        disclaimer = "Behind this mask there is more than just flesh. Beneath this mask there is an idea... and ideas are bulletproof"

    [params.social]
        GitHub = "vukilis"
        Steam = "vuk1lis"
        Linkedin = "vuklekic"
        Email = "vuk.lekic@vukilis.com"
    
    [params.page]
        rssFullText = true
        [params.page.comment]
            enable = true
            [params.page.comment.valine]
                enable = false
            [params.page.comment.utterances]
                enable = true
                # owner/repo
                repo = "vukilis/website"
                issueTerm = "url"
                label = "comment"
                lightTheme = "github-dark"
                darkTheme = "github-dark"
    
    [params.analytics]
        enable = true
        # Yandex Metrica
        [params.analytics.yandexMetrica]
        id = "97163691"

        [params.analytics.google]
        id = "G-BPK5CT0MGQ"
        anonymizeIP = true

[markup]
    [markup.highlight]
        # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
        noClasses = false

custom_css = ["css/_custom.scss"]